services:
  oracle:
    extends:
      file: deps.yaml
      service: oracle

  keycloak:
    extends:
      file: deps.yaml
      service: keycloak

  puppet:
    extends:
      file: deps.yaml
      service: puppet

  mailhog:
    extends:
      file: deps.yaml
      service: mailhog

  demo:
    hostname: demo
    container_name: demo
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'demo'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
      KEYCLOAK_FRONTEND_SERVER_URL: 'http://localhost:8081'
      KEYCLOAK_BACKEND_SERVER_URL: 'http://keycloak:8080'
      ORACLE_DATASOURCE: 'demo'
      ORACLE_SERVER: 'oracle:1521'
      ORACLE_USER: 'DEMO_OWNER'
      ORACLE_PASS: 'password'
      ORACLE_SERVICE: 'xepdb1'
      PUPPET_SHOW_SERVER_URL: 'http://puppet:3000'
      BACKEND_SERVER_URL: 'http://demo:8080'
      FRONTEND_SERVER_URL: 'https://localhost:8443'
      TZ: 'America/New_York'
      DEMO_FEEDBACK_SENDER_ADDRESS: 'cnm@example.com'
      DEMO_FEEDBACK_TO_ADDRESS_CSV: 'recipient1@example.com,recipient2@example.com'
      DEMO_CONTENT_CONTACT: 'bob@example.com'
      DEMO_TECHNICAL_CONTACT: 'larry@example.com'
      DEMO_DOC_CSV: 'https://github.com/JeffersonLab/smoothness-template|DEMO Home'